/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class p5Kinect_P5Kinect */

#ifndef _Included_p5Kinect_P5Kinect
#define _Included_p5Kinect_P5Kinect
#ifdef __cplusplus
extern "C" {
#endif
#undef p5Kinect_P5Kinect_CNT
#define p5Kinect_P5Kinect_CNT 5L
/*
 * Class:     p5Kinect_P5Kinect
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_p5Kinect_P5Kinect_init
  (JNIEnv *, jobject);

/*
 * Class:     p5Kinect_P5Kinect
 * Method:    Nui_GetImage
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_p5Kinect_P5Kinect_Nui_1GetImage
  (JNIEnv *, jobject);

/*
 * Class:     p5Kinect_P5Kinect
 * Method:    Nui_GetDepth
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_p5Kinect_P5Kinect_Nui_1GetDepth
  (JNIEnv *, jobject);

/*
 * Class:     p5Kinect_P5Kinect
 * Method:    Nui_GetMask
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_p5Kinect_P5Kinect_Nui_1GetMask
  (JNIEnv *, jobject);

/*
 * Class:     p5Kinect_P5Kinect
 * Method:    getFigure
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_p5Kinect_P5Kinect_getFigure
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
